language: ruby
services:
  - postgresql
before_script:
  - psql -c 'create database whispr_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rake spec
  - bundle exec rake spec:features
