env:
  global:
    # Talvez isso devesse ser um secret no Travis :thinking:
    - CC_TEST_REPORTER_ID=4d782e3f27eeabeabe8185e9c98f1a00aeb311c336998eeac6d9ca6e80ea2755
language: ruby
services:
  - postgresql
before_install:
  # Instalar dependências do Capybara-Webkit
  - sudo apt-get update
  - sudo apt-get install -y g++ qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
before_script:
  # Configurar reporter de test coverage do CodeClimate.
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  # Configurar DB de teste.
  - psql -c 'create database whispr_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rake spec
  # Rodar o cucumber em um servidor X virtual, para utilizar o WebKit.
  - xvfb-run bundle exec cucumber
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT